title: SULO OWL Pizza Tutorial
remote_theme: just-the-docs/just-the-docs
description: "A principled workflow for ontology engineering from conceptualization to implementation."

  
# This adds a simple sidebar or top nav depending on the theme
nav:
  - text: Home
    url: /
  - text: ESWC 2026
    url: /events/eswc2026/
  - text: GitHub Repo
    url: https://github.com/maastrichtu-ids/sulo-owl-pizza-tutorial
