title: SULO OWL Pizza Tutorial
description: "A principled workflow for ontology engineering from conceptualization to implementation."
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

  
# This adds a simple sidebar or top nav depending on the theme
nav:
  - text: Home
    url: /
  - text: ESWC 2026
    url: /events/eswc2026
  - text: GitHub Repo
    url: https://github.com/maastrichtu-ids/sulo-owl-pizza-tutorial
